[Export]
baked_notebookfile = true
slider_server_url="https://aniketjivani.github.io/ME599_Static/"


[SliderServer]
# port = 8080
# host = "0.0.0.0"



# You can also set Pluto's configuration here:
#[Pluto]
#[Pluto.compiler]
#threads = 2
